(define-key gnus-group-mode-map (kbd ";")	'gnus-group-read-group)
(define-key gnus-group-mode-map (kbd "b")	'gnus-group-best-unread-group)
(define-key gnus-group-mode-map (kbd "k")	'gnus-group-next-group)
(define-key gnus-group-mode-map (kbd "l")	'gnus-group-prev-group)
(define-key gnus-group-mode-map (kbd "u")	'gnus-group-first-unread-group)
(define-key gnus-group-mode-map (kbd "RET")	'gnus-group-enter-server-mode)
(define-key gnus-group-mode-map (kbd "[")	'gnus-group-prev-unread-group)
(define-key gnus-group-mode-map (kbd "]")	'gnus-group-next-unread-group)
(define-key gnus-group-mode-map (kbd "{")	'gnus-group-prev-unread-group-same-level)
(define-key gnus-group-mode-map (kbd "}")	'gnus-group-next-unread-group-same-level)

