(setcdr c-mode-map		nil)
(setcdr conf-mode-map		nil)
(setcdr dired-mode-map		nil)
(setcdr gnus-group-mode-map	nil)
(setcdr gnus-mode-map		nil)
(setcdr gnus-server-mode-map	nil)
(setcdr makefile-mode-map	nil)
(setcdr org-mode-map		nil)
