;; (load-theme 'almost-mono-white t)
;; (load-theme 'humanoid-light t)
;; (load-theme 'lambda-dark t)
;; (load-theme 'lambda-light t)
;; (load-theme 'less t)
;; (load-theme 'mindre t)
;; (load-theme 'monotropic t)
(load-theme 'nothing t)
;; (load-theme 'stimmung-themes-light t)
;; (load-theme 'tao-yang t)
;; (load-theme 'writerish t)
;; (stimmung-themes-load-light)

