(add-to-list 'load-path "~/Internet/Git/Emacs/Window-Manager/exwm/")
(add-to-list 'load-path "~/Internet/Git/Emacs/Window-Manager/xelb/")

(load-file "~/Internet/Git/Emacs/Utility/emacs-eat.git/eat.elc")
(load-file "~/Internet/Git/Emacs/Utility/tempel.git/tempel.el")
(add-to-list 'load-path "/usr/share/emacs/site-lisp/emms/")
(load-file "/usr/share/emacs/site-lisp/mailutils-mh.el")
(add-to-list 'load-path "~/Internet/Git/Emacs/Utility/with-editor/lisp/")
(add-to-list 'load-path "~/Internet/Git/Emacs/Utility/dash.el/")
(add-to-list 'load-path "~/Internet/Git/Emacs/Git/magit/lisp/")
(load-file "/usr/share/gtags/gtags.el")
(add-to-list 'load-path "/usr/share/emacs/site-lisp/exheres-mode/")
(add-to-list 'load-path "~/Internet/Git/Emacs/Utility/emacs-pcre/")
(load-file "~/Internet/Git/Emacs/Utility/hop.el/hop.el")
(load-file "~/Internet/Git/Emacs/Modeline/feline/feline.el")
(load-file "~/Internet/Git/Emacs/Utility/goto-last-point/goto-last-point.el")
(add-to-list 'load-path "~/Internet/Git/Emacs/Utility/embark/")
(add-to-list 'load-path "/home/wymux/Internet/Git/Emacs/Completion/hotfuzz/")
(add-to-list 'load-path "/home/wymux/Internet/Git/Emacs/Utility/eev/")
(load-file "~/Internet/Git/Emacs/Mode/keyfreq/keyfreq.el")

(require 'eat)
(require 'eev-load)
(require 'embark)
(require 'emms)
(require 'emms-history)
(require 'emms-playlist-mode)
(require 'emms-player-mpd)
(require 'emms-setup)
(require 'exheres-mode)
(require 'exwm)
(require 'exwm-randr)
(require 'gnus)
(require 'hotfuzz)
(require 'hotfuzz-module)
(require 'keyfreq)
(require 'magit)
(require 'pcre)

