(setq enable-recursive-minibuffers t)
(define-key minibuffer-local-completion-map (kbd "SPC") 'self-insert-command)
(define-key minibuffer-local-completion-map (kbd "C-SPC") 'minibuffer-complete-word)
(define-key minibuffer-mode-map (kbd "C-n") 'icomplete-forward-completions) 
(define-key minibuffer-mode-map (kbd "C-p") 'icomplete-backward-completions) 
