(blink-cursor-mode -1)
(global-eldoc-mode -1)
(global-hl-line-mode 1)
(global-so-long-mode 1)
(global-tempel-abbrev-mode 1)
(goto-last-point-mode 1)
(recentf-mode 1)
(savehist-mode 1)
(winner-mode 1)

(setq use-short-answers t)
(setq kill-buffer-query-functions nil)
(setq-default bidi-display-reordering nil)
(setq transient-history-file nil)
(setq Man-notify-method 'pushy)
(setq ffap-require-prefix nil)
(setq-default cursor-in-non-selected-windows nil)
(setq scroll-margin 0)
(setq completions-format 'horizontal)
(setq completions-header-format nil)
(setq completions-max-height 10)
(setq completion-auto-select t)

(define-key minibuffer-mode-map (kbd "C-n") 'minibuffer-next-completion) 
(define-key minibuffer-mode-map (kbd "C-p") 'minibuffer-previous-completion) 
