(blink-cursor-mode -1)
(feline-mode 1)
(global-eldoc-mode -1)
(global-hl-line-mode 1)
(global-so-long-mode 1)
(global-tempel-abbrev-mode 1)
(goto-last-point-mode 1)
(keyfreq-mode 1)
(keyfreq-autosave-mode 1)
(icomplete-mode 1)
(recentf-mode 1)
(repeat-mode 1)
(save-place-mode 1)
(tab-bar-mode 1)
(tab-bar-history-mode 1)
(winner-mode 1)

(setq use-short-answers t)
(setq kill-buffer-query-functions nil)
(setq-default bidi-display-reordering nil)
(setq transient-history-file nil)
(setq Man-notify-method 'pushy)
(setq ffap-require-prefix nil)
(setq-default cursor-in-non-selected-windows nil)
(setq scroll-margin 0)
(setq max-mini-window-height 0.1)
(setq epg-pinentry-mode 'loopback)
(setenv "GPG_AGENT_INFO" nil)
