(ryo-modal-major-mode-keys
 'gnus-server-mode
 ("a"	gnus-server-add-server)
 ("c"	gnus-server-close-server)
 ("d"	gnus-server-deny-server)
 ("e"	gnus-server-edit-server)
 ("k"	gnus-server-kill-server)
 ("l"	gnus-server-list-servers)
 ("m"	gnus-server-copy-server)
 ("o"	gnus-server-offline-server)
 ("r"	gnus-server-regenerate-server)
 ("s"	gnus-server-scan-server)
 ("y"	gnus-server-yank-server)
 ("C-b"	gnus-bug)
 ("C-c"	gnus-server-close-all-servers)
 ("C-h"	gnus-info-find-node)
 ("C-o"	gnus-server-open-all-servers)
 ("C-r"	gnus-server-remove-denials)
)
