;; Alphabet

(define-key global-map (kbd "a") 'self-insert-command)
(define-key global-map (kbd "b") 'self-insert-command)
(define-key global-map (kbd "c") 'self-insert-command)
(define-key global-map (kbd "d") 'self-insert-command)
(define-key global-map (kbd "e") 'self-insert-command)
(define-key global-map (kbd "f") 'self-insert-command)
(define-key global-map (kbd "g") 'self-insert-command)
(define-key global-map (kbd "h") 'self-insert-command)
(define-key global-map (kbd "i") 'self-insert-command)
(define-key global-map (kbd "j") 'self-insert-command)
(define-key global-map (kbd "k") 'self-insert-command)
(define-key global-map (kbd "l") 'self-insert-command)
(define-key global-map (kbd "m") 'self-insert-command)
(define-key global-map (kbd "n") 'self-insert-command)
(define-key global-map (kbd "o") 'self-insert-command)
(define-key global-map (kbd "p") 'self-insert-command)
(define-key global-map (kbd "q") 'self-insert-command)
(define-key global-map (kbd "r") 'self-insert-command)
(define-key global-map (kbd "s") 'self-insert-command)
(define-key global-map (kbd "t") 'self-insert-command)
(define-key global-map (kbd "u") 'self-insert-command)
(define-key global-map (kbd "v") 'self-insert-command)
(define-key global-map (kbd "w") 'self-insert-command)
(define-key global-map (kbd "x") 'self-insert-command)
(define-key global-map (kbd "y") 'self-insert-command)
(define-key global-map (kbd "z") 'self-insert-command)

;; Number

(define-key global-map (kbd "1") 'self-insert-command)
(define-key global-map (kbd "2") 'self-insert-command)
(define-key global-map (kbd "3") 'self-insert-command)
(define-key global-map (kbd "4") 'self-insert-command)
(define-key global-map (kbd "5") 'self-insert-command)
(define-key global-map (kbd "6") 'self-insert-command)
(define-key global-map (kbd "7") 'self-insert-command)
(define-key global-map (kbd "8") 'self-insert-command)
(define-key global-map (kbd "9") 'self-insert-command)
(define-key global-map (kbd "0") 'self-insert-command)

;; Shift-number

(define-key global-map (kbd "!") 'self-insert-command)
(define-key global-map (kbd "@") 'self-insert-command)
(define-key global-map (kbd "#") 'self-insert-command)
(define-key global-map (kbd "$") 'self-insert-command)
(define-key global-map (kbd "%") 'self-insert-command)
(define-key global-map (kbd "^") 'self-insert-command)
(define-key global-map (kbd "&") 'self-insert-command)
(define-key global-map (kbd "*") 'self-insert-command)
(define-key global-map (kbd "(") 'self-insert-command)
(define-key global-map (kbd ")") 'self-insert-command)

;; Other

(define-key global-map (kbd "`") 'self-insert-command)
(define-key global-map (kbd "~") 'self-insert-command)
(define-key global-map (kbd "-") 'self-insert-command)
(define-key global-map (kbd "_") 'self-insert-command)
(define-key global-map (kbd "=") 'self-insert-command)
(define-key global-map (kbd "+") 'self-insert-command)
(define-key global-map (kbd "[") 'self-insert-command)
(define-key global-map (kbd "{") 'self-insert-command)
(define-key global-map (kbd "]") 'self-insert-command)
(define-key global-map (kbd "}") 'self-insert-command)
(define-key global-map (kbd "\\") 'self-insert-command)
(define-key global-map (kbd "|") 'self-insert-command)
(define-key global-map (kbd ";") 'self-insert-command)
(define-key global-map (kbd ":") 'self-insert-command)
(define-key global-map (kbd "'") 'self-insert-command)
(define-key global-map (kbd "\"") 'self-insert-command)
(define-key global-map (kbd ",") 'self-insert-command)
(define-key global-map (kbd "<") 'self-insert-command)
(define-key global-map (kbd ".") 'self-insert-command)
(define-key global-map (kbd ">") 'self-insert-command)
(define-key global-map (kbd "/") 'self-insert-command)
(define-key global-map (kbd "?") 'self-insert-command)

(define-key global-map (kbd "A") 'self-insert-command)
(define-key global-map (kbd "B") 'self-insert-command)
(define-key global-map (kbd "C") 'self-insert-command)
(define-key global-map (kbd "D") 'self-insert-command)
(define-key global-map (kbd "E") 'self-insert-command)
(define-key global-map (kbd "F") 'self-insert-command)
(define-key global-map (kbd "G") 'self-insert-command)
(define-key global-map (kbd "H") 'self-insert-command)
(define-key global-map (kbd "I") 'self-insert-command)
(define-key global-map (kbd "J") 'self-insert-command)
(define-key global-map (kbd "K") 'self-insert-command)
(define-key global-map (kbd "L") 'self-insert-command)
(define-key global-map (kbd "M") 'self-insert-command)
(define-key global-map (kbd "N") 'self-insert-command)
(define-key global-map (kbd "O") 'self-insert-command)
(define-key global-map (kbd "P") 'self-insert-command)
(define-key global-map (kbd "Q") 'self-insert-command)
(define-key global-map (kbd "R") 'self-insert-command)
(define-key global-map (kbd "S") 'self-insert-command)
(define-key global-map (kbd "T") 'self-insert-command)
(define-key global-map (kbd "U") 'self-insert-command)
(define-key global-map (kbd "V") 'self-insert-command)
(define-key global-map (kbd "W") 'self-insert-command)
(define-key global-map (kbd "X") 'self-insert-command)
(define-key global-map (kbd "Y") 'self-insert-command)
(define-key global-map (kbd "Z") 'self-insert-command)

(define-key global-map (kbd "SPC") 'self-insert-command)
