(add-to-list 'load-path "~/Internet/Git/Emacs/Utility/compat/")
(load-file "~/Internet/Git/Emacs/Utility/with-editor/lisp/with-editor.el")
(load-file "~/Internet/Git/Emacs/Utility/dash.el/dash.el")
(add-to-list 'load-path "~/Internet/Git/Emacs/Git/magit/lisp/")
(require 'magit)
