(ryo-modal-key
	"h"	'(
		  ("a"		apropos-command)
		  ("b"		describe-bindings)
		  ("c"		describe-key-briefly)
		  ("d"		apropos-documentation)
		  ("e"		view-echo-area-messages)
		  ("f"		describe-function)
		  ("g"		describe-gnu-project)
		  ("h"		view-hello-file)
		  ("i"		info)
		  ("k"		describe-key)
		  ("l"		view-lossage)
		  ("m"		describe-mode)
		  ("n"		view-emacs-news)
		  ("o"		describe-symbol)
		  ("p"		finder-by-keyword)
		  ("r"		info-emacs-manual)
		  ("s"		describe-syntax)
		  ("t"		help-with-tutorial)
		  ("v"		describe-variable)
		  ("w"		where-is)
		  ("C-a"	about-emacs)
		  ("C-c"	describe-copying)
		  ("C-d"	view-emacs-debugging)
		  ("C-e"	view-external-packages)
		  ("C-f"	view-emacs-FAQ)
		  ("C-h"	help-for-help)
		  ("C-i"	describe-input-method)
		  ("C-n"	view-emacs-news)
		  ("C-o"	describe-distribution)
		  ("C-p"	view-emacs-problems)
		  ("C-s"	search-forward-help-for-help)
		  ("C-t"	view-emacs-todo)
		  ("C-w"	describe-no-warranty)
		  )
)
