(ryo-modal-major-mode-keys
  'Info-mode
    ("l"	Info-scroll-down)
    ("k"	Info-scroll-up)
    ("j"	Info-backward-node)
    (";"	Info-forward-node)
    ("b"	Info-history-back)
    ("f"	Info-history-forward)
    ("["	Info-prev)
    ("]"	Info-next)

    ("d"	Info-directory)
    ("C-h"	Info-history)
    ("i"	Info-index)
    ("g"	Info-goto-node)
    ("m"	Info-menu)
    ("u"	Info-up)
    ("C-b"	beginning-of-buffer)
    ("C-e"	end-of-buffer)
    ("C-f"	Info-follow-reference)
)
