(ryo-modal-keys
	(:norepeat t)
	("-"	negative-argument)
	("0"	digit-argument)
	("1"	digit-argument)
	("2"	digit-argument)
	("3"	digit-argument)
	("4"	digit-argument)
	("5"	digit-argument)
	("6"	digit-argument)
	("7"	digit-argument)
	("8"	digit-argument)
	("9"	digit-argument)
)
