(ryo-modal-keys
    ("," ryo-modal-repeat)
    ("i" ryo-modal-mode)
    ("j" backward-char)
    ("k" next-line)
    ("l" previous-line)
    (";" forward-char)
    ("C-j" windmove-left)
    ("C-k" windmove-down)
    ("C-l" windmove-up)
    ("C-;" windmove-right)
)
