(setq inhibit-startup-screen t)

(add-to-list 'load-path "~/Internet/Git/Emacs/almost-mono-themes/")
(add-to-list 'load-path "~/Internet/Git/Emacs/ef-themes/")
(add-to-list 'custom-theme-load-path "~/Internet/Git/Emacs/ef-themes/")
(add-to-list 'custom-theme-load-path "~/Internet/Git/Emacs/almost-mono-themes/")
(load-file "~/Internet/Git/Emacs/mindre-theme/mindre-theme.elc")
(load-file "~/.config/emacs/elpaca/builds/dash/dash.elc")
(load-file "~/Internet/Git/Emacs/autothemer/autothemer.el")
(load-file "~/Internet/Git/Emacs/emacs-theme-cyanometric/cyanometric-theme.el")
(load-file "~/Internet/Git/Emacs/emacs-theme-vegetative/vegetative-theme.el")
;; (load-theme 'almost-mono-white t)
(load-theme 'mindre t)
;; (load-theme 'cyanometric t)
